### ISSUE TITLE
Two applications often appear for the same address, at the same time, for the same thing

### ISSUE THREAD

**Issue by henare** [planningalerts-scrapers/bellingen-shire#5]
e.g.
* https://www.planningalerts.org.au/applications/775867
* https://www.planningalerts.org.au/applications/775866

It's because one's a Development Application and one's a Construction Certificate. We're currently collecting both, along with Complying Developments, Trees, and Modification Applications.

We obviously want Development Applications. I think we want Complying Development, Trees, and Modification Applications because these inform people about what's going on in their area. It also means, for example, if people comment on Complying Developments (which probably aren't subject to formal submissions) then it indicates that maybe it shouldn't be a complying development, or that complying developments also need to allow formal submissions.

However is there any reason to collect Construction Certificates?

If not we just need to drop the `CC` in the query string from [the URL we're looking at](https://github.com/planningalerts-scrapers/bellingen-shire/blob/master/scraper.rb#L8):

`http://infomaster.bellingen.nsw.gov.au/MasterViewLive/modules/applicationmaster/default.aspx?page=found&1=thismonth&4a=DA,CC,CDC,TA,MD&6=F`

**Comment by LoveMyData** [comment]
@henare I think we should publish whatever council is publishing, otherwise, where do we draw the line what to publish or not? So we don't involves on 'council' decision what to publish. We are working as a information collector.

Besides, for bigger development, DA and CC are not normally together.

**Comment by henare** [comment]
Thanks for your thoughts on this @LoveMyData :sparkles: 

>I think we should publish whatever council is publishing, otherwise, where do we draw the line what to publish or not?

The most important principle here is to do what's right by the people using PlanningAlerts. Showing duplicate alerts is annoying and confusing so makes alerts less useful to people. If we can avoid it then that would be best.

People can affect the outcome of a DA but a CC doesn't mean much for most people (it just applies to a building that's already been finished). So that's why I was questioning if we should collect them or not.

**Comment by henare** [comment]
Revisiting this again today I think it's a good idea to remove CCs from our search. The duplicates in the list of the [search including CCs](http://infomaster.bellingen.nsw.gov.au/MasterViewLive/modules/applicationmaster/default.aspx?page=found&1=thismonth&4a=DA,CC,CDC,TA,MD&6=F) contain nothing extra over the [search that excludes the CCs](http://infomaster.bellingen.nsw.gov.au/MasterViewLive/modules/applicationmaster/default.aspx?page=found&1=thismonth&4a=DA,CDC,TA,MD&6=F). I'm going to make this change now.
